// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using EFCore04_2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EFCore04_2.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<SelectAllProductsResult>> SelectAllProductsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<TenMostExpensiveProductsResult>> TenMostExpensiveProductsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
